# Generated by Django 2.0.9 on 2019-01-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('appok', models.BooleanField(default=True)),
                ('failreason', models.TextField(blank=True, max_length=1024)),
                ('dependencies', models.ManyToManyField(blank=True, to='appstatus.Application')),
            ],
        ),
    ]
