# Generated by Django 2.0.9 on 2019-01-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('service_url', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('serviceok', models.BooleanField(default=True)),
                ('failreason', models.TextField(blank=True, max_length=1024)),
                ('application', models.ForeignKey(null=True, on_delete='CASCADE', related_name='services', to='appstatus.Application')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='services', to='appstatus.Service')),
            ],
        ),
    ]
